{{Form::texto('name', 		Lang::get('client.name'))}}
{{Form::texto('last_name', 	Lang::get('client.lastName'))}}
{{Form::texto('dni', 		Lang::get('client.document'))}}
{{Form::texto('address', 	Lang::get('client.address'))}}
{{Form::texto('email', 		Lang::get('client.email'))}}
{{Form::texto('phone', 		Lang::get('client.phoneNumber'))}}
{{Form::texto('cell_phone', Lang::get('client.cellPhoneNumber'))}}
{{Form::texto('company_name', 	Lang::get('client.company'))}}
{{Form::texto('cuit', 			Lang::get('client.cuit'))}}
{{Form::medicalinsurance('medicalinsurance_id', Lang::get("client.medicalInsurance"))}}